### ISSUE TITLE
李老师推荐的论文

### ISSUE THREAD

**Issue by SkyFan2002** [RethinkFS/docs#2]
- [ ] ConfD: Analyzing Configuration Dependencies of File Systems for Fun and Profit. FAST 2023
- [ ] #4
- [ ] On Stacking a Persistent Memory File System on Legacy File Systems. FAST 2023
- [ ] pFSCK: Accelerating File System Checking and Repair for Modern Storage. FAST 2021
- [ ] Pattern-Guided File Compression with User-Experience Enhancement for Log-Structured File System on Mobile Devices. FAST 2021

需要调研在zenfs上实现的可行性，以及和flash的相关性。

**Comment by chiro2001** [comment]
https://www.zotero.org/groups/5024037/chiro2001/collections/XJK8SB5V
